### ISSUE TITLE
Update dependences required

### ISSUE THREAD

**Issue by Apcio** [grofit/aurelia-files#1]
Hi.
The newest aurelia-framework is 0.13.2, this version of aurelia-files is not compatible with dependecy of framework 0.12.0.

**Comment by grofit** [comment]
many joys, is there anything else which needs updating or is it just the dependency on framework? as I can quickly do that via github without checking it out.

**Comment by Apcio** [comment]
Changing to "github:aurelia/framework@^0.13.2" should be enough. From my side it works now.

**Comment by grofit** [comment]
Done
