### ISSUE TITLE
jspm install not working

### ISSUE THREAD

**Issue by itfourp** [grofit/aurelia-files#4]
I tried this:

```
$ jspm install grofit/aurelia-files
     Updating registry cache...

err  Repo jspm:grofit/aurelia-files not found.

warn Installation changes not saved.
```

Did I miss anything?

**Comment by itfourp** [comment]
Solved the problem:
`$ jspm install github:grofit/aurelia-files`

**Comment by grofit** [comment]
I think different versions of JSPM use different approaches, i didnt think you needed the github bit though in newer versions.

**Comment by itfourp** [comment]
I guess there's a configuration for that somewhere. By the way, will this plugin be available for commercial use (have you decided for a license yet)?

**Comment by grofit** [comment]
oh sorry all my plugins are available for everyone to use for anything, I just never remember to put licenses in explicitly.

**Comment by itfourp** [comment]
That's awesome! Thank you for you quick response :+1:

**Comment by grofit** [comment]
its done now, enjoy.

**Comment by sibire20** [comment]
i have used this to install **$ jspm install github:grofit/aurelia-files** , now it throws error 'GET /src/aurelia-files.js" Error (404): "Not found"', also new to aurelia Js.

**Comment by grofit** [comment]
that implies that the jspm installation has not worked correctly as that sort of error (When it looks for `<module-name>.js` in the root) implies it cannot find the module in the config file so it looks for a js file in the root as a last ditch attempt to load it.
