### ISSUE TITLE
typo in file-reader-helper

### ISSUE THREAD

**Issue by isaacHagoel** [grofit/aurelia-files#6]
i might be wrong (just started playing with this) but looks like in line 16 in file-reader-helper:
`if(typeof(errorCallback) == "function")`

should be:
`if(typeof(onError) == "function")`

**Comment by grofit** [comment]
Should be fixed in 0.1.3 there was also a typo in `onProgress` it is based upon the knockout.files binding (as are most of these) so I think it was basically argument changes, anyway should be fixed now.
